import {
  ArchiveIcon,
  CrumpledPaperIcon,
  CubeIcon,
  DiscIcon,
  FileTextIcon,
  GearIcon,
  ImageIcon,
  LockClosedIcon,
  MixIcon,
  Pencil1Icon,
  VideoIcon
} from "@radix-ui/react-icons";
import {
  BracesIcon,
  CodeIcon,
  FileTerminalIcon,
  GitBranch,
  Heading,
  Library,
  MusicIcon
} from "lucide-react";

const fileIconMap = new Map([
  ["png", <ImageIcon className="w-full h-full" />],
  ["jpg", <ImageIcon className="w-full h-full" />],
  ["jpeg", <ImageIcon className="w-full h-full" />],
  ["gif", <ImageIcon className="w-full h-full" />],
  ["webp", <ImageIcon className="w-full h-full" />],
  ["svg", <ImageIcon className="w-full h-full" />],
  ["bmp", <ImageIcon className="w-full h-full" />],
  ["ico", <ImageIcon className="w-full h-full" />],
  ["tiff", <ImageIcon className="w-full h-full" />],
  ["txt", <FileTextIcon className="w-full h-full" />],
  ["doc", <FileTextIcon className="w-full h-full" />],
  ["iso", <DiscIcon className="w-full h-full" />],
  ["zip", <ArchiveIcon className="w-full h-full" />],
  ["tar", <ArchiveIcon className="w-full h-full" />],
  ["rar", <ArchiveIcon className="w-full h-full" />],
  ["7zip", <ArchiveIcon className="w-full h-full" />],
  ["gz", <ArchiveIcon className="w-full h-full" />],
  ["exe", <CubeIcon className="w-full h-full" />],
  ["appimage", <CubeIcon className="w-full h-full" />],
  ["deb", <CubeIcon className="w-full h-full" />],
  ["rpm", <CubeIcon className="w-full h-full" />],
  ["apk", <CubeIcon className="w-full h-full" />],
  ["dmg", <CubeIcon className="w-full h-full" />],
  ["msi", <CubeIcon className="w-full h-full" />],
  ["pkg", <CubeIcon className="w-full h-full" />],
  ["pdf", <FileTextIcon className="w-full h-full" />],
  ["mp3", <MusicIcon className="w-full h-full" size={16} />],
  ["wav", <MusicIcon className="w-full h-full" size={16} />],
  ["flac", <MusicIcon className="w-full h-full" size={16} />],
  ["ogg", <MusicIcon className="w-full h-full" size={16} />],
  ["mp4", <VideoIcon className="w-full h-full" />],
  ["mkv", <VideoIcon className="w-full h-full" />],
  ["webm", <VideoIcon className="w-full h-full" />],
  ["avi", <VideoIcon className="w-full h-full" />],
  ["mov", <VideoIcon className="w-full h-full" />],
  ["tmp", <CrumpledPaperIcon className="w-full h-full" />],
  ["log", <CrumpledPaperIcon className="w-full h-full" />],
  ["bak", <CrumpledPaperIcon className="w-full h-full" />],
  ["sys", <GearIcon className="w-full h-full" />],
  ["cfg", <GearIcon className="w-full h-full" />],
  ["conf", <GearIcon className="w-full h-full" />],
  ["ini", <GearIcon className="w-full h-full" />],
  ["dll", <Library className="w-full h-full" size={16} />],
  ["dat", <FileTextIcon className="w-full h-full" />],
  ["gitignore", <GitBranch className="w-full h-full" size={16} />],
  ["git", <GitBranch className="w-full h-full" size={16} />],
  ["gitattributes", <GitBranch className="w-full h-full" size={16} />],
  ["gitmodules", <GitBranch className="w-full h-full" size={16} />],
  ["gitconfig", <GitBranch className="w-full h-full" size={16} />],
  ["gitkeep", <GitBranch className="w-full h-full" size={16} />],
  ["ps1", <FileTerminalIcon className="w-full h-full" size={16} />],
  ["sh", <FileTerminalIcon className="w-full h-full" size={16} />],
  ["bash", <FileTerminalIcon className="w-full h-full" size={16} />],
  ["zsh", <FileTerminalIcon className="w-full h-full" size={16} />],
  ["fish", <FileTerminalIcon className="w-full h-full" size={16} />],
  ["bat", <FileTerminalIcon className="w-full h-full" size={16} />],
  ["cmd", <FileTerminalIcon className="w-full h-full" size={16} />],
  ["asm", <MixIcon className="w-full h-full" />],
  ["json", <BracesIcon className="w-full h-full" size={16} />],
  ["html", <Heading className="w-full h-full" size={16} />],
  ["htm", <Heading className="w-full h-full" size={16} />],
  ["xml", <Heading className="w-full h-full" size={16} />],
  ["lock", <LockClosedIcon className="w-full h-full" />],
  ["js", <CodeIcon className="w-full h-full" size={16} />],
  ["ts", <CodeIcon className="w-full h-full" size={16} />],
  ["jsx", <CodeIcon className="w-full h-full" size={16} />],
  ["tsx", <CodeIcon className="w-full h-full" size={16} />],
  ["css", <Pencil1Icon className="w-full h-full" />],
  ["scss", <Pencil1Icon className="w-full h-full" />],
  ["sass", <Pencil1Icon className="w-full h-full" />],
  ["c", <CodeIcon className="w-full h-full" size={16} />],
  ["cpp", <CodeIcon className="w-full h-full" size={16} />],
  ["h", <CodeIcon className="w-full h-full" size={16} />],
  ["hpp", <CodeIcon className="w-full h-full" size={16} />],
  ["java", <CodeIcon className="w-full h-full" size={16} />],
  ["py", <CodeIcon className="w-full h-full" size={16} />],
  ["rb", <CodeIcon className="w-full h-full" size={16} />],
  ["php", <CodeIcon className="w-full h-full" size={16} />],
  ["go", <CodeIcon className="w-full h-full" size={16} />],
  ["rs", <CodeIcon className="w-full h-full" size={16} />],
  ["lua", <CodeIcon className="w-full h-full" size={16} />],
  ["pl", <CodeIcon className="w-full h-full" size={16} />],
  ["swift", <CodeIcon className="w-full h-full" size={16} />],
  ["kt", <CodeIcon className="w-full h-full" size={16} />],
  ["dart", <CodeIcon className="w-full h-full" size={16} />],
  ["cs", <CodeIcon className="w-full h-full" size={16} />],
  ["scala", <CodeIcon className="w-full h-full" size={16} />]
]);

export { fileIconMap };
