// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {fs} from '../models';
import {context} from '../models';

export function CreateEntry(arg1:string,arg2:boolean):Promise<void>;

export function DeleteEntries(arg1:Array<string>):Promise<void>;

export function FetchDisks():Promise<Array<fs.Disk>>;

export function FetchKnownFolders():Promise<{[key: string]: string}>;

export function ListDir(arg1:string):Promise<Array<fs.DirEntry>>;

export function OpenFiles(arg1:Array<string>):Promise<void>;

export function RenameEntry(arg1:string,arg2:string):Promise<void>;

export function SetContext(arg1:context.Context):Promise<void>;

export function StarEntries(arg1:Array<fs.DirEntry>):Promise<void>;

export function StartDirWatcher():Promise<void>;

export function StartFetchDisksInterval():Promise<void>;

export function UnstarEntries(arg1:Array<string>):Promise<void>;
