// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {fs} from '../models';
import {context} from '../models';

export function CreateEntry(arg1:string,arg2:boolean):Promise<void>;

export function DeleteEntries(arg1:Array<string>):Promise<void>;

export function FetchConfigDir():Promise<string>;

export function FetchDisks():Promise<Array<fs.Disk>>;

export function FetchKnownFolders():Promise<Array<string>>;

export function Init(arg1:context.Context):Promise<void>;

export function ListDir(arg1:string):Promise<Array<fs.DirEntry>>;

export function StartFetchDisksInterval():Promise<void>;

export function StartWatcher():Promise<void>;
